spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://localhost:3306/wine_cellar?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
                username: root
                password: 123456
            second:  #数据源2
                url: jdbc:mysql://localhost:3306/wine_cellar?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
                username: root
                password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
                        
file:
    upload:
        baseurl: http://${project.host.name}/renren-fast/file/
        saveurl: D:/upload/image/
project:
    host:
        name: 127.0.0.1:8080

#支付宝支付参数配置
ali:
    appId: 2018121362505805
    keyPublic: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5poa4NRR+aZ5Dw5PA5/fbq88Qi0/FBeK3/CMAXPyNNsK3Zv2ywNrn6NCtiERmz506iztAEJUtQvhPU4mXANV+Bs01yKl8jNucbYK/mebrlYYR34rc81PCD6YwsKRQ1+kx7GvtmlCxZ0eq5P/tpvOKn7pFxs12HINZhVSqCJp6XDAs0XvcQLmxzc2vH4f8yD9KYBShxDbsU0aFJg0tRcrfT207vjcQVjgdVFQCNWYnQzKemDW4L3gukDLBQbgqZPq98nO5qfHUv3nZs27vc0uQrgN+CGVfG7YeSkRL3Y5bBTV3X+joEJG+oaVaIatIowhgfrqs+J55syI2pQ0K+d4YwIDAQAB
    keyPrivate: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCwzNK7Egtcb8Qp7uSgpFcJa2VzOWJWSODUsO4RDNy1yIbIkN0IZR9LYsciP0ntK6HZfkH8o6CbQTQhw5oT+weT9PxcI19Y/2z7AeXBSImJXqu/r2LDlykzrCvcGzOqX5AycnHD3fB9yvmwy7iqfCuFmBiV+mAC1xgzdJQl4iLB+K6byEIisYcM+2muuS34EM/INsUVAloQNcRDXC0d1j2Hj/rThGVXtxQvGFhaQPApsIYiETMiSPc163krB3pJOqvjW07DebjvemWF8ORf8KiIlvEr0ed1BTSjIAeP6119RH0zWwc12UC6Cn3iK/uJQx4qFPXCD6mO0pl6oT3r6VgvAgMBAAECggEBAJK+rvpOk9d5fRxBCMq9HPDYjzAAJTrw6owe/rpwLpFDi3vVoWBiboMnzZkDZtzQJlpbjXGgbqHukNKlg7Gp3jRUV1IymeVIvK/qd0TibCX0yiEj9ZnaUXxuH0ll2pBDGXCFxR+Jix8d5fl0XiZDQex0vZNeaWpyFcg/rudytt6/pRQ6yC7upv0NTGrDNlTtPEQTUHyJZMvkI+WL2W7xP0K2JjasEWtozQpOecUcksZjsZBGjswh6hk/k9yaTgy0+RzsX4CqFItZiB/lF5fUl4c0l4ESwMvT6IYfY5QZmDHqqAoP3M81dGE6i8iLTgAmwaj9s/q91a1WGZ9YzJU5jcECgYEA2LOn8+b7oOkARq5htms418hVkL4nPI09qLuIoNZg+Z6O5KS4B6xrpQoz6kjXSLJeZf1Hgu+fKRwZldlzahl2HE7DxTqkBErD6Y4npQq7MFjq84KeBJUTE6itWRcHd4QGOPfyGhg34JKJIbBFutleMEvlMRD/YI8mSKkC1fJQmxkCgYEA0Ny83taR2+uGE5VchpczCb7I/jMUaXuff+p4WJdzirX7an7oCcAHfjB9oHIHq8gphTvPZYaQBfVUTT7gAl+ui8TVTL51ouwkw1hjzWZuy1sLO2+9CScLUJ1XIfcph8HYz1NzInhMoLYNeB3WG5XzMJ9LqYtGAm2S8dJNzFcDvocCgYEArNcerrsdGEq/naCY7xa2T+XJ2ZjRUsqU03BAmYhj8LU248c9wWEUup5YqhVPIPyjrlVGJHlbST7QaWT3WTjVq95m53jOOV4oxLBNjqXwh69kNrWHs7/zZ0qyeMyVeA4lqGqa/5UxfD1kgypFc7LMHVlrhKc6CZojvvCPAnYzNIECgYEAvuDdI3JJfwkyUXdxRfesxz07B0W7Y+N9EzQ/pAdVqvFBwkQU38RFlMfQJ+/OnumhOIg+tHRT734T+zx5EPJM3KOYpDhz3d+egYCoRTFWFDcyfrFRu6mZJ6WD2iC+Lbm04VVMpbX3ofB/QsVRxYg25rrONTZ5VwK5BpPCUfs8CsUCgYEAlxsFUcgCGI8Al1oC2VwSNgkg+qj/ZxhuiPV9bz0bv6KHCH1zooKcLgtnMJIo3ur2Or3mkWN0A5H2IDAlVN1rE/aY0ahCm7wrmtWh056GNFUKdHVlOxdUT6Y4Zn40HH9wCWyknPZZcjzPgsTbTwrawI4j7iHRul4Ghasa8jN7RGg=
    notifyUrl: http://${project.host.name}/app/cellarcallback/paySuccess${settlementtype}/${methodpayment}
    keyPrivateCertPwd: cth/UVKp3WGP0MBG6PTbqA==
#微信支付参数配置
wechat:
    appid: wx0c49da4788b737ac
    mchId: 1323577401
    secretKey: tcjj1234tcjj1234tcjj1234tcjj1234
    notifyUrl: http://${project.host.name}/app/cellarcallback/paySuccess${settlementtype}/${methodpayment}